// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7TxtB8D9-mAFtjBsGEXto9lV7jodeY8',
    appId: '1:171016321341:web:a1dee15f06ef422c0f6d54',
    messagingSenderId: '171016321341',
    projectId: 'mylaptop-94cb2',
    authDomain: 'mylaptop-94cb2.firebaseapp.com',
    storageBucket: 'mylaptop-94cb2.firebasestorage.app',
    measurementId: 'G-JB4WJ2585H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYpnxpbsv9iY1Yw43E9jlL_dHMh7wDXvM',
    appId: '1:171016321341:android:35b034a943ee81cf0f6d54',
    messagingSenderId: '171016321341',
    projectId: 'mylaptop-94cb2',
    storageBucket: 'mylaptop-94cb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Y5EDwpCfqJFrxWQQny52lJVfLRJ-qoM',
    appId: '1:171016321341:ios:289ce09a86627ce30f6d54',
    messagingSenderId: '171016321341',
    projectId: 'mylaptop-94cb2',
    storageBucket: 'mylaptop-94cb2.firebasestorage.app',
    iosBundleId: 'com.example.laptop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Y5EDwpCfqJFrxWQQny52lJVfLRJ-qoM',
    appId: '1:171016321341:ios:289ce09a86627ce30f6d54',
    messagingSenderId: '171016321341',
    projectId: 'mylaptop-94cb2',
    storageBucket: 'mylaptop-94cb2.firebasestorage.app',
    iosBundleId: 'com.example.laptop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7TxtB8D9-mAFtjBsGEXto9lV7jodeY8',
    appId: '1:171016321341:web:639b2c92f32a622f0f6d54',
    messagingSenderId: '171016321341',
    projectId: 'mylaptop-94cb2',
    authDomain: 'mylaptop-94cb2.firebaseapp.com',
    storageBucket: 'mylaptop-94cb2.firebasestorage.app',
    measurementId: 'G-P8QSJ0RRSN',
  );
}
